# Generated by Django 5.2.7 on 2025-10-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20)),
                ('plan', models.CharField(choices=[('matematica', 'Matemática'), ('comunicacion', 'Comunicación'), ('ambos', 'Matemática + Comunicación')], max_length=50)),
                ('cupo_maximo', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
